In [ ]:
import numpy as np

In [ ]:
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [ ]:
#y = np.array([[0],[0],[1],[1]])
y = np.array([[0,0,1,1]]).T
y

array([[0],
       [0],
       [1],
       [1]])

In [ ]:
def activation(x:float, deriv=False):
  if deriv == True:
    return x*(1-x)
  else:
    return 1/(1+np.exp(-x))

In [ ]:
np.random.seed(2025)
syn0 = 2 * np.random.random((3,1)) - 1
syn0

array([[-0.72902367],
       [ 0.77570341],
       [ 0.86521128]])

In [ ]:
epochs = 10000
for i in range(epochs):
  #Forward pass
  l0 = X  #layer 0, input layer
  l1 = activation(np.dot(l0, syn0), deriv=False)
  l1_error = y - l1 #Medicion de la magnitud del error que tuve

  #Backward pass
  l1_delta = l1_error * activation(l1, deriv=True)
  syn0 += np.dot(l0.T, l1_delta)

print("Output:")
print(l1)
print("Weights:")
print(syn0)


Output:
[[0.00967058]
 [0.00786652]
 [0.99358834]
 [0.99211528]]
Weights:
[[ 9.67225666]
 [-0.20829193]
 [-4.6290006 ]]


In [ ]:
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [ ]:
y = np.array([[0,1,1,0]]).T
y

array([[0],
       [1],
       [1],
       [0]])

In [ ]:
syn0 = 2 * np.random.random((3,4)) - 1
syn1 = 2 * np.random.random((4,1)) - 1

display(syn0)
display(syn1)

array([[-0.10886367, -0.22352891, -0.48480713,  0.31473517],
       [-0.01476612,  0.92847684,  0.60196895, -0.08958943],
       [ 0.60211617, -0.91656405,  0.53891574, -0.99365777]])

array([[-0.41438122],
       [ 0.22182867],
       [ 0.82605478],
       [-0.39976999]])

In [ ]:
epochs = 60000
for i in range(epochs):
  #forwar pass
  l0 = X
  l1 = activation(np.dot(l0, syn0), deriv=False)
  l2 = activation(np.dot(l1, syn1), deriv=False)
  l2_error = y - l2
  #Backward pass
  l2_delta = l2_error * activation(l2, deriv=True)
  l1_error = np.dot(l2_delta, syn1.T)
  l1_delta = l1_error * activation(l1, deriv=True)
  syn1 = syn1 + np.dot(l1.T, l2_delta)
  syn0 = syn0 + np.dot(l0.T, l1_delta)

print("Output:")
print(l2)

print("Weights:")
display(syn0)
display(syn1)

Output:
[[0.00283979]
 [0.99590307]
 [0.99499518]
 [0.00514029]]
Weights:


array([[-6.09148105, -7.21878625,  2.37656693, -0.0288378 ],
       [ 7.25189335,  6.24993578,  1.75584868,  0.55934077],
       [ 2.76806028, -3.1358687 ,  1.18423109, -1.13892992]])

array([[-11.53926317],
       [ 11.94318621],
       [  5.78628841],
       [  0.2817676 ]])